---
abstract: 'Catmandu modules for working with DOI data.'
author:
  - 'Wouter Willaert <wouterw@inuits.eu>'
build_requires:
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-DOI
provides:
  Catmandu::DOI:
    file: lib/Catmandu/DOI.pm
    version: 0.02
  Catmandu::Importer::DOI:
    file: lib/Catmandu/Importer/DOI.pm
requires:
  Catmandu: 0.0302
  Furl: 0.41
  Moo: 1.000003
  XML::LibXML::Simple: 0.91
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
